Support bridge confguration on segment
vmware/terraform-provider-nsxt pull request #784
Opened 2022-08-31 19:58 UTC by annakhm

Add policy_bridge_profile data source and bridge_config clause
on segments.

Signed-off-by: Anna Khmelnitsky <akhmelnitsky@vmware.com>

2022-08-31 20:28 UTC, annakhm commented
/test-all

2022-08-31 20:30 UTC, annakhm commented
/test-all

2022-08-31 21:14 UTC, annakhm commented
/test-all

2022-08-31 22:22 UTC, annakhm commented
/test-all

2022-09-19 12:23 UTC, ksamoray requested changes

2022-09-19 12:23 UTC, ksamoray commented on nsxt/segment_common.go
> +			Description: "Beidge configuration",
Bridge?

2022-09-21 18:08 UTC, annakhm commented on nsxt/segment_common.go
> +			Description: "Beidge configuration",
Thanks, fixed

2022-09-22 17:49 UTC, 2ez4szliu approved these changes

2022-09-22 21:31 UTC, merged

2022-10-06 21:33 UTC, ajgrinnell commented
Thank you for working on this. I seem to be getting errors still even with the latest provider. I have pieced together what I can from the code and think I have it, but its still not working. If you have any ideas I would appreciate it. 

╷
│ Error: Unsupported block type
│ 
│   on segments.tf line 13, in resource "nsxt_policy_segment" "Overlay_Segment":
│   13:   bridge_config {
│ 
│ Blocks of type "bridge_config" are not expected here.
 terraform plan -var-file="secret.tfvars" 

##
│ Error: Invalid data source
│ 
│   on main.tf line 35, in data "nsxt_policy_bridge_profile" "TEST-Edge-Bridge":
│   35: data "nsxt_policy_bridge_profile" "TEST-Edge-Bridge" {
│ 
│ The provider vmware/nsxt does not support data source "nsxt_policy_bridge_profile".

##
 terraform version
Terraform v1.3.1
on linux_amd64
+ provider registry.terraform.io/vmware/nsxt v3.2.8

2023-04-27 00:24 UTC, annakhm commented
Hi @ajgrinnell, sorry for late response, I've missed this comment. Bridge support was added with version 3.2.9